//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Execution_of_Darkness_Wikia.Pages.Articles
{
    public partial class ArticleEdit
    {
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Panel pnlEdit;
        protected global::System.Web.UI.WebControls.TextBox txtArticleTitle;
        protected global::System.Web.UI.WebControls.TextBox txtSummary;
        protected global::System.Web.UI.WebControls.TextBox txtContent;
        protected global::System.Web.UI.WebControls.TextBox txtChangeSummary;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnPreview;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlPreview;
        protected global::System.Web.UI.WebControls.Literal litPreviewTitle;
        protected global::System.Web.UI.WebControls.Literal litPreviewSummary;
        protected global::System.Web.UI.WebControls.Literal litPreviewContent;
        protected global::System.Web.UI.WebControls.Button btnBackToEdit;
        protected global::System.Web.UI.WebControls.Panel pnlHistory;
        protected global::System.Web.UI.WebControls.Repeater rptVersions;
    }
}
