//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Execution_of_Darkness_Wikia.Pages.Articles
{
    public partial class ArticleList
    {
    }
}
