//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Execution_of_Darkness_Wikia.Pages.Admin
{
    public partial class SchemaCompare
    {
        protected global::System.Web.UI.WebControls.Literal litExpectedTables;
        protected global::System.Web.UI.WebControls.Literal litActualTables;
        protected global::System.Web.UI.WebControls.Literal litDifferenceCount;
        protected global::System.Web.UI.WebControls.Panel pnlOk;
        protected global::System.Web.UI.WebControls.Panel pnlGrid;
        protected global::System.Web.UI.WebControls.GridView gvSchemaDiffs;
    }
}
