//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Execution_of_Darkness_Wikia
{
    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litSubtitle;
        protected global::System.Web.UI.WebControls.Repeater rptFactions;
        protected global::System.Web.UI.WebControls.Repeater rptCharacters;
        protected global::System.Web.UI.WebControls.Repeater rptLocations;
        protected global::System.Web.UI.WebControls.Repeater rptSystems;
        protected global::System.Web.UI.WebControls.Repeater rptTimeline;
    }
}
